### ISSUE TITLE
Deprecated link to pretrained models?

### ISSUE THREAD

**Issue by jereliu** [stanford-oval/zero-shot-multiwoz-acl2020#1]
The link to the pretrained models (https://oval.cs.stanford.edu/releases/acl2020/) seem not accessible anymore.

**Comment by gcampax** [comment]
Sorry, that was a misconfiguration on our server. The link is working now.

**Comment by nqchieutb01** [comment]
Hi, your papers have been incredibly helpful! Unfortunately, I'm having trouble accessing the link for models and the augmented dataset (https://oval.cs.stanford.edu/releases/acl2020/). Could you please double-check the link or let me know if there's an alternative way to access them? Thanks so much!
