### ISSUE TITLE
Questions about multiwoz augmentation using genie

### ISSUE THREAD

**Issue by SongHoSung** [stanford-oval/zero-shot-multiwoz-acl2020#2]
hi 
I read your good paper well.
So, I want to generate a new dataset, but the structure of genie seems to be a little different.
Could you tell me how to run it according to the changed genie?

1. In genie's generate-dialogs, there is no target called 'multidst' and there is only 'thingstalk' and 'dlgthingtalk'.

2. Some genie files seem to have changed their names or locations.
- domain-%.genie , first-turn.genie , contextual.genie, shared.genie (i found)
- Do I have to make above the genie files?

3. I tried making it in genie-toolkit/starter/multiwoz/ in genie-toolkit, and templates and synthetic forms seem to be different with trade-dst's augment.

Please reply.
Thank you.

**Comment by gcampax** [comment]
Hello!

The code to support the paper in this repository was removed from the most recent version of genie-toolkit. If you would like to reproduce our paper, please use the version of genie-toolkit listed in the README.

The "multiwoz" starter folder you found in the most recent genie-toolkit is instead related to [this other paper](https://arxiv.org/abs/2009.07968).

I hope this answered your question. Please reopen if you have any more questions.

**Comment by SongHoSung** [comment]
Thank you for your kind reply.

I have one more question.

When using multiwoz in the latest genie starter, is it possible for the result to be in multiwoz form? 
 Like the file you shared (https://oval.cs.stanford.edu/releases/acl2020/dataset/augmented.tar.xz)
If not, I would like to change the genie version to augment it.
When i made it as a thinktalk target, i need to create a new parsing rule because it is not matched with trade-dst/data_analysis's parse_belief().
